language ::= (expression ('\r\n'|'\n')? )+

expression ::= 'fd' distance| 'bk' distance | 'rt' angle | 'lt' angle | 'cs' | 'pu' | 'pd' | 'ht' | 'st' | 'home' | 'label' (word | string) | 'setxy' number number | 'repeat' integer '[' expression ']' | 'make' word (value | word | string) | 'print' (value | word | string)

distance ::= number

angle ::= number

number ::= '0-9'+ '.'? '0-9'*

integer ::= '0-9'+

word ::= '"' 'a-Z'+

string ::= '[' 'a-Z '+ ']'

value ::= (number | math_function | variable ) ( operator (number | math_function | variable))*

variable ::= ':' word

math_function ::= 'random' integer | 'cos' number  | 'sin' number  | 'tan' number  | 'arccos' number  | 'arcsin' number  | 'arctan' number | 'sqrt' number | 'ln' number | 'power' number number 

operator ::= '+' | '-' | '*' | '/'