language ::= (expression ('\r\n'|'\n')? )+

expression ::= 'fd' numeric_value| 'bk' numeric_value | 'rt' numeric_value | 'lt' numeric_value | 'cs' | 'pu' | 'pd' | 'ht' | 'st' | 'home' | 'label' value | 'setxy' numeric_value numeric_value | 'repeat' numeric_value '[' expression ']' | 'make' word value | 'print' value | 'if' numeric_value boolean_operator numeric_value '[' expression ']'

value ::= word | string | text_variable | numeric_value

numeric_value ::=  '('? (number | math_function | numeric_variable ) ')'? ( operator '('? (number | math_function | numeric_variable ) ')'?)*

text_variable ::= ':' word

numeric_variable ::= ':' word

math_function ::= 'random' integer | 'cos' number  | 'sin' number  | 'tan' number  | 'arccos' number  | 'arcsin' number  | 'arctan' number | 'sqrt' number | 'ln' number | 'power' number number 

number ::= '0-9'+ '.'? '0-9'*

integer ::= '0-9'+

word ::= '"' 'a-Z'+

string ::= '[' 'a-Z '+ ']'

operator ::= '+' | '-' | '*' | '/'

boolean_operator ::= '<' | '>' | '==' | '<=' | '>=' | '!='